# Generated by Django 3.2.15 on 2022-09-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapp", "0002_auto_20220919_1745"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(null=True, verbose_name="date of birth"),
        ),
    ]
